<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dpf"
 *
 * Auto generated by Extension Builder 2014-10-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Qucosa Publication',
	'description' => '',
	'category' => 'plugin',
	'author' => 'effective WEBWORK GmbH',
	'author_email' => 'info@effective-webwork.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => 'uploads/tx_dpf',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',                                            
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);