#!/bin/bash

## Description: Install TYPO3 and the Extension using typo3cms command
## Usage: first-install

composer install
vendor/bin/typo3cms install:setup -n  --use-existing-database --database-name db
vendor/bin/typo3cms configuration:set 'BE/debug' 1
vendor/bin/typo3cms configuration:set 'FE/debug' 1
vendor/bin/typo3cms configuration:set 'SYS/devIPmask' '*'
vendor/bin/typo3cms configuration:set 'SYS/displayErrors' 1
vendor/bin/typo3cms configuration:set 'SYS/systemLogLevel' 0
vendor/bin/typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
vendor/bin/typo3cms configuration:set 'MAIL/transport' 'smtp'
vendor/bin/typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
vendor/bin/typo3cms configuration:set 'GFX/processor' 'ImageMagick'
vendor/bin/typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
vendor/bin/typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'
vendor/bin/typo3cms install:generatepackagestates
vendor/bin/typo3cms cache:flush