#!/bin/bash
#ddev-silent-no-warn

## Description: Install TYPO3 and the Extension using typo3cms command
## Usage: first-install

composer install --no-security-blocking
rm -f public/typo3conf/LocalConfiguration.php

# dpf's standalone vendor/ conflicts with TYPO3's class alias loader when present.
# Move it to container-local /tmp for the duration of the TYPO3 setup commands.
if [ -d /var/www/kitodo-publication/vendor ]; then
    cp -r /var/www/kitodo-publication/vendor /tmp/dpf-vendor-backup
    rm -rf /var/www/kitodo-publication/vendor
fi

vendor/bin/typo3cms install:setup -n  --use-existing-database --database-name db
vendor/bin/typo3cms configuration:set 'BE/debug' 1
vendor/bin/typo3cms configuration:set 'FE/debug' 1
vendor/bin/typo3cms configuration:set 'SYS/devIPmask' '*'
vendor/bin/typo3cms configuration:set 'SYS/displayErrors' 1
vendor/bin/typo3cms configuration:set 'SYS/systemLogLevel' 0
vendor/bin/typo3cms configuration:set 'SYS/trustedHostsPattern' '.*.*'
vendor/bin/typo3cms configuration:set 'MAIL/transport' 'smtp'
vendor/bin/typo3cms configuration:set 'MAIL/transport_smtp_server' 'localhost:1025'
vendor/bin/typo3cms configuration:set 'GFX/processor' 'ImageMagick'
vendor/bin/typo3cms configuration:set 'GFX/processor_path' '/usr/bin/'
vendor/bin/typo3cms configuration:set 'GFX/processor_path_lzw' '/usr/bin/'
vendor/bin/typo3cms install:generatepackagestates
vendor/bin/typo3cms cache:flush

if [ -d /tmp/dpf-vendor-backup ]; then
    mv /tmp/dpf-vendor-backup /var/www/kitodo-publication/vendor
fi
