#!/bin/bash

## Usage: test [options]

executable="vendor/phpunit/phpunit/phpunit"
options="-c vendor/nimut/testing-framework/res/Configuration/UnitTests.xml"

vendor/phpunit/phpunit/phpunit \
  -c vendor/nimut/testing-framework/res/Configuration/UnitTests.xml \
  src/Tests \
  $@ 
