#!/bin/bash

## Description: Run unit tests inside web container
## Usage: test [options]

executable="vendor/phpunit/phpunit/phpunit"
options="-c vendor/nimut/testing-framework/res/Configuration/UnitTests.xml"

$executable $options ../kitodo-publication/Tests $@
