name: kitodo-publication-dpf
type: php
docroot: public
php_version: "7.4"
webserver_type: apache-fpm
xdebug_enabled: false
no_project_mount: true
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.6"
performance_mode: none
hooks:
    post-import-db:
        - exec: vendor/bin/typo3cms database:updateschema
        - exec: vendor/bin/typo3cms cleanup:updatereferenceindex
    pre-stop:
        - exec: rm fcrepo-home/data/*.lock.db
          service: fcrepo
use_dns_when_possible: true
composer_version: ""
web_environment: []
corepack_enable: false
